### ISSUE TITLE
Make it so Waifu goes behind text, but not behind other elements

### ISSUE THREAD

**Issue by AndroidKitKat** [AndroidKitKat/waifupaste.moe#12]
In certain scenario (like on a mobile phone) the girl can be behind the text at the bottom of the page. This is undesirable.

**Comment by JorgeDaboub** [comment]
Looking to help out with this issue. Would the desired scenario be that the girl stays on top of the text at all times?

**Comment by AndroidKitKat** [comment]
Sorry, but I thought about it, and I don't really want this feature anymore. Feel free to take a crack at #6 or #7 and stretch your JavaScript muscles!

**Comment by JorgeDaboub** [comment]
I was going to for Issue #7 but it appears this is already a function on the website?
